# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nokia/msm8998-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter NB1 A1N B2N C1N CTL DDV DRG PL2 SLD TAS,$(TARGET_DEVICE)),)

endif
