# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nokia/msm8998-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),msm8998-common)

endif
